name: AdoAgents 
variables:
  - template: ../../ado/env/global.yml
  - template: ../../ado/env/central.yml
  - template: variables.yml
trigger:
  - main
stages:
  - stage: Central 
    jobs:
    - deployment: Central
      pool:
        vmImage: 'ubuntu-latest'
      environment: ${{ variables.centralEnvironmentName }}
      strategy:
        runOnce:
          deploy:
            steps:
            - template: deploy-initial-infrastructure.yml
              parameters:
                appName: ${{ variables.appName }}
                location: ${{ variables.location }}
                resourceGroupName: ${{ variables.centralResourceGroupName }}
                azureServiceConnection: ${{ variables.serviceConnectionName }}
                pathToAdoAgentsDirectory: ${{ variables.pathToAdoAgentsDirectory }}
                environmentName: ${{ variables.centralEnvironmentName }}
            - template: build-image.yml
              parameters:
                resourceGroupName: ${{ variables.centralResourceGroupName }}
                containerRegistryName: $(containerRegistryName)
                imageName: ${{ variables.adoImageName }}
                imageVersion: ${{ variables.adoImageVersion }}
                azureServiceConnection: ${{ variables.serviceConnectionName }}
                pathToAdoAgentDockerfile: ${{ variables.pathToAdoAgentDockerfile }}
                environmentName: ${{ variables.centralEnvironmentName }}
            - template: deploy-ado-build-agents.yml
              parameters:
                appName: ${{ variables.appName }}
                location: ${{ variables.location }}
                resourceGroupName: ${{ variables.centralResourceGroupName }}
                azpPool: ${{ variables.adoAgentPoolName }}
                azpToken: $(azpToken)
                azpUrl: ${{ variables.adoUrl }}
                imageName: ${{ variables.adoImageName }}
                imageVersion: ${{ variables.adoImageVersion }}
                containerRegistryName: $(containerRegistryName)
                logAnalyticsWorkspaceName: $(logAnalyticsWorkspaceName)
                azureServiceConnection: ${{ variables.serviceConnectionName }}
                pathToAdoAgentsDirectory: ${{ variables.pathToAdoAgentsDirectory }}
                environmentName: ${{ variables.centralEnvironmentName }}
                
