parameters:
  - name: resourceGroupName
  - name: azureServiceConnection
  - name: environmentName
  - name: imageName
  - name: imageVersion
  - name: containerRegistryName
  - name: pathToAdoAgentDockerfile

steps:
  - task: AzureCLI@2
    inputs:
      azureSubscription: ${{ parameters.azureServiceConnection }}
      scriptType: bash
      scriptLocation: inlineScript
      inlineScript: |
        az acr build --image ${{ parameters.imageName }}:${{ parameters.imageVersion}} --registry ${{ parameters.containerRegistryName }} ${{ parameters.pathToAdoAgentDockerfile }}