parameters:
  - name: resourceGroupName
  - name: azureServiceConnection
  - name: pathToAdoAgentsDirectory
  - name: environmentName
  - name: appName
  - name: location

steps:
  - checkout: self
    persistCredentials: true
  - template: ../global/printEnv.yml
  - task: AzureCLI@2
    displayName: Deploy Initial Infrastructure
    inputs:
      azureSubscription: ${{ parameters.azureServiceConnection }}
      scriptType: bash
      scriptLocation: inlineScript
      inlineScript: |
        az deployment group create --resource-group ${{ parameters.resourceGroupName }} \
                                   --template-file ${{ parameters.pathToAdoAgentsDirectory }}/initial-infrastructure/main.bicep \
                                   --parameters appName=${{ parameters.appName }} \
                                   --parameters location=${{ parameters.location }} \
                                   --parameters environment=${{ parameters.environmentName }}

        echo 'convert outputs to variables'
        echo $deploymentoutputs | jq -c '. | to_entries[] | [.key, .value.value]' |
        while IFS=$"\n" read -r c; do
          outputname=$(echo "$c" | jq -r '.[0]')
          outputvalue=$(echo "$c" | jq -r '.[1]')
          echo "setting variable $outputname=$outputvalue"
          echo "##vso[task.setvariable variable=$outputname]$outputvalue"
        done